### ISSUE TITLE
Servlet returns 404 Not Found at the /solr/dovecot/ endpoint

### ISSUE THREAD

**Issue by yurivanmidden** [lmm-git/docker-dovecot-solr#4]
Hi,

In my case, with `http://<container_name>:8983/solr/dovecot/` configured in Dovecot, a **404 Not Found** is returned. I can't really figure out why, as it seems that the dovecot core is up and running, according to the Solr admin panel:

![afbeelding](https://user-images.githubusercontent.com/6409975/131664937-e204a612-7cd2-4c11-b6bd-b1654cb064dc.png)

My docker-compose.yml:
```yml
...

mail_solr:
    image: lmmdock/dovecot-solr:latest
    container_name: mail_solr
    hostname: solr
    restart: unless-stopped
    volumes:
      - "mail-fts:/opt/solr/server/solr/dovecot"
    networks:
      - mail
...
 ```
10-plugins.conf
```
mail_plugins = $mail_plugins fts fts_solr

plugin {
  fts = solr
  fts_autoindex = yes
  fts_solr = url=http://solr:8983/solr/dovecot/ 
}
```
Am I missing something here?
